### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by notlimahrelyt** [mrkno/PlexSSO#1]
Hi, i'm confused about what this project is used for.

I've run the install process, but it seems to always load the error page.

![image](https://user-images.githubusercontent.com/5624324/38781009-e52947e6-40ac-11e8-845c-abe721a0ed80.png)

I wish this had some screenshots or a guide.

**Comment by drkno** [comment]
Yeah, sorry about that. I never imagined anyone else actually using it.... what instructions that are there are simply to remind me of what I did next time I have to debug it (not to say that it shouldn't be used, having an SSO for Sonarr, Radarr, etc is really nice).

The specific problem with your deployment relates to the `webroot` setting in `auth/config/production.json`. `webroot` is a relative path from the directory you started the server in to the `sso/build` directory. If you are having difficulty with this setting, a quick workaround is to copy the entire contents of `sso/build` to `auth/public`, replacing all conflicts.

So this is what it will look like after it is deployed successfully:
![image](https://user-images.githubusercontent.com/6830312/38783109-f1b387ba-4151-11e8-97b5-1766093fae58.png)

Some better, manual instructions for getting this working from the beginning - these instructions assume Linux/macOS, but with some small adaption do work on Windows:
1. `cd` into the `sso` directory
2. `npm install && npm run build`
3. `cd` into the `auth` directory
4. `npm install`
5. Inside the `auth/config` directory, create the following files:
    - `production.json`
    - `passwords.json`
Refer to [build.sh](https://github.com/mrkno/PlexSSO/blob/master/build.sh) for the format of these files.
Ensure you edit each of these files to suit your needs before continuing.
6. `cd` into the `auth` directory and run `NODE_ENV=production node src/index.js`

**Comment by notlimahrelyt** [comment]
Hey thanks for getting back to me.

So i've followed the steps above, but am now running into:

> root@login:/opt/PlexSSO/sso# npm install && npm run build
> 
> > uglifyjs-webpack-plugin@0.4.6 postinstall /opt/PlexSSO/sso/node_modules/uglifyjs-webpack-plugin
> > node lib/post_install.js
> 
> added 1294 packages in 29.65s
> 
> > @plexauth/sso@0.1.0 build /opt/PlexSSO/sso
> > react-scripts build
> 
> Creating an optimized production build...
> Compiled successfully.
> 
> File sizes after gzip:
> 
>   62.33 KB  build/static/js/main.d99480e0.js
>   632 B     build/static/css/main.c6bb914a.css
> 
> The project was built assuming it is hosted at the server root.
> To override this, specify the homepage in your package.json.
> For example, add this to build it for GitHub Pages:
> 
>   "homepage" : "http://myname.github.io/myapp",
> 
> The build folder is ready to be deployed.
> You may serve it with a static server:
> 
>   npm install -g serve
>   serve -s build
> 
> root@login:/opt/PlexSSO/sso# cd ../auth/
> root@login:/opt/PlexSSO/auth# npm install
> added 113 packages in 2.732s
> root@login:/opt/PlexSSO/auth# cd config/
> root@login:/opt/PlexSSO/auth/config# nano production.json
> root@login:/opt/PlexSSO/auth/config# nano passwords.json
> root@login:/opt/PlexSSO/auth/config# cd ..
> root@login:/opt/PlexSSO/auth# NODE_ENV=production node src/index.js
> /opt/PlexSSO/auth/src/strategy/basicauth.js:6
>     for (let password of passwords) {
>                          ^
> 
> TypeError: passwords is not iterable
>     at module.exports.passwords (/opt/PlexSSO/auth/src/strategy/basicauth.js:6:26)
>     at Object.<anonymous> (/opt/PlexSSO/auth/src/index.js:21:43)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Function.Module.runMain (module.js:693:10)
>     at startup (bootstrap_node.js:188:16)
>     at bootstrap_node.js:609:3
> root@login:/opt/PlexSSO/auth# 

Also in the production.json file, i'm not sure what "cookiedomain" is.
And in the passwords.json file, i'm not sure what "name" is.

**Comment by drkno** [comment]
Your error means that your `passwords.json` is in the wrong format - you probably had the outer-most scope as an object (`{}`) not an array (`[]`). Here is mine (edited to remove passwords obviously) as an example:
```js
[
    {
        "name": "common",
        "username": "admin",
        "password": "<my password>",
        "sabnzbdUrl": "http://127.0.0.1:8080",
        "jackettUrl": "http://127.0.0.1:9117"
    },
    {
        "name": "transmission",
        "username": "transmission",
        "password": "<my transmission password>"
    }
]
```

> Also in the production.json file, i'm not sure what "cookiedomain" is.  

Refer to "Scope of Cookies" on this page: [https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies). It is the domain scoping of your cookie, e.g. a cookie set for `plex.mydomain.com` would also usable on `sonarr.plex.mydomain.com` and `login.plex.mydomain.com` but not `mydomain.com`.

>  And in the passwords.json file, i'm not sure what "name" is.

The Nginx configuration uses it to retrieve the correct username/password combination for the service being accessed, see example [here](https://github.com/mrkno/PlexSSO/blob/master/nginx/sonarr.conf#L20). Setting the `X-PlexSSO-Basic` header to `common` in Nginx using my example passwords.json above would retrieve HTTP Basic Credentials `admin:<my password>`. Setting it to `transmission` would retrieve `transmission:<my transmission password>`.

----

In case it is useful, here is an example of my production.json as well:
```js
{
    "webroot": "../sso/build",
    "cookiedomain": "plex.mydomain.com",
    "plexservername": "<my plex server name>",
    "plexserverclientidentifier": "<my plex client ID>",
    "fanarttvapikey": "<my fanart.tv api key>"
}
```

**Comment by notlimahrelyt** [comment]
Okay, So i've made those adjustments, no more errors in the terminal, but nothing loads at mydomain.com:4200 - If I go directly to mydomain.com, it just shows the "Welcome to NGINX" default page.

> root@login:/opt/PlexSSO/auth# nano config/passwords.json 
> root@login:/opt/PlexSSO/auth# nano config/p
> passwords.json   production.json  
> root@login:/opt/PlexSSO/auth# nano config/production.json 
> root@login:/opt/PlexSSO/auth# NODE_ENV=production node src/index.js
> Cached basic-auth password for common
> Cached jackett password for common
> Listening at http://*:4200

I appreciate your help, i'm not very good with nginx so this is all new to me. I'd love to get this running though, I have a huge use for SSO with plex credentials.

**Comment by drkno** [comment]
Something should load at :4200, but if the application says it has started I believe it.
What you are missing now is the Nginx configuration. I suggest you just get Nginx up and running without the SSO, first pointing at an applications such as Sonarr and Radarr (e.g. point both `sonarr.plex.mydomain.com` and `radarr.plex.mydomain.com` at the same Nginx instance, make them each reverse proxy to the appropriate application). I am not an Nginx expert, so google and a page like [this one](https://www.techandme.se/set-up-nginx-reverse-proxy/) might help you with that.

Once you have Nginx working without an SSO, you will need to update the configuration to use it. I have example Nginx configurations in the [Nginx directory](https://github.com/mrkno/PlexSSO/tree/master/nginx). The Sonarr configuration in particular is almost exactly what you want (with a few mods I use that configuration).

Ensure that you enable basic authentication rather than form-based for the applications that will be behind the SSO.

**Comment by notlimahrelyt** [comment]
Alright. We've got a login page. Plex credentials do not login in though "User does not have access".

> root@login:/opt/PlexSSO/auth# NODE_ENV=production node src/index.js
> Cached basic-auth password for common
> Listening at http://*:4200
> GET / 304 - - 6.697 ms
> GET /static/css/main.c6bb914a.css 304 - - 1.908 ms
> GET /static/js/main.d99480e0.js 304 - - 1.436 ms
> GET /api/v1/sso 401 17 - 7.923 ms
> GET /logo.png 304 - - 0.775 ms
> GET / 304 - - 0.710 ms
> GET /favicon.ico 302 33 - 7.033 ms
> GET /index.html 200 668 - 3.857 ms
> GET /api/v1/background/ 304 - - 217.698 ms
> GET /api/v1/backgroundProxy/ 302 33 - 1.307 ms
> GET /index.html 304 - - 0.794 ms
> POST /api/v1/login 401 63 - 793.311 ms

Thoughts?

**Comment by drkno** [comment]
Either you are typing your username and password incorrectly or you need to check `plexservername` and `plexserverclientidentifier` in production.json.
`plexservername` is exactly what you would expect it to be - the name of your plex server. `plexserverclientidentifier` is the GUID that uniquely identifies your plex server. You can get this a lot of different ways, the easiest being opening the network console in your web-browser, loading plex and looking at the response to the request that it made to http://myplexserver:32400/servers or http://myplexserver:32400/users
